# 请保存为UTF-8格式

spring:
 profiles:
  active: 
  - dev

---
server:
 # 注册中心占用 7001 端口， 冒号后面必须要有空格
 port: 7001

spring:
 # 开发环境
 profiles: dev
 application:
  name: microservicecloud-config-eureka-client

eureka:
 instance:
  # 冒号后面必须要有空格
  hostname: eureka7001.com
 client:
  # 当前的 eureka-server 自己不注册进服务列表中
  register-with-eureka: false
  # 不通过 eureka 获取注册信息
  fetch-registry: false
  service-url:
   defaultZone: http://eureka7001.com:7001/eureka

---
server:
 # 注册中心占用 7001 端口， 冒号后面必须要有空格
 port: 7001

spring:
 # 测试环境
 profiles: test
 application:
  name: microservicecloud-config-eureka-client

eureka:
 instance:
  # 冒号后面必须要有空格
  hostname: eureka7001.com
 client:
  # 当前的 eureka-server 自己不注册进服务列表中
  register-with-eureka: false
  # 不通过 eureka 获取注册信息
  fetch-registry: false
  service-url:
   defaultZone: http://eureka7001.com:7001/eureka
